import RegistrationEntryEditor from "@/components/admin/RegistrationEntryEditor";
import { editableEntry } from "@/lib/tournamentEntryEditing";
import { requireAdmin } from "@/lib/auth";
import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { PLAYER_REPORT_COLUMNS, selectedColumns, buildReportQuery } from "@/lib/reports";
import PdfPreview from "@/components/admin/PdfPreview";
export default async function PlayerReport({searchParams}:{searchParams:Promise<any>}) {
 await requireAdmin("tournament_registrations");const sp=await searchParams;const all=sp.entries==="all";
 const s=createSupabaseServiceClient();let q=s.from("tournament_registrations").select("*, tournaments(title)");
 if(sp.tournament_id)q=q.eq("tournament_id",sp.tournament_id);
 if(!all)q=q.eq("payment_status","paid").eq("registration_status","confirmed");
 const {data,error}=await q.order("last_name").order("first_name");
 const {data:tournaments}=await s.from("tournaments").select("id,title").order("title");
 const rows=data||[];const cols=selectedColumns("tournament_registrations",PLAYER_REPORT_COLUMNS);
 const base={tournament_id:sp.tournament_id,report:"players",entries:all?"all":"confirmed"};
 const csv=buildReportQuery(base,"tournament_registrations",PLAYER_REPORT_COLUMNS,"csv");const pdf=buildReportQuery(base,"tournament_registrations",PLAYER_REPORT_COLUMNS,"pdf");
 return <div><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-extrabold">Tournament Player Report</h1><a href="/club-admin/tournament-registrations" className="btn-secondary">Registration Report</a></div><p className="mt-2 text-stone-600">Player details for preparing Vega files. CSV columns can be mapped in your import workflow. This is not a native Vega tournament file.</p><form className="card mt-5 flex flex-wrap gap-3 p-5"><label><span className="admin-label">Tournament</span><select name="tournament_id" defaultValue={sp.tournament_id||""} className="admin-input"><option value="">All tournaments</option>{(tournaments||[]).map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label><span className="admin-label">Entries</span><select name="entries" defaultValue={all?"all":"confirmed"} className="admin-input"><option value="confirmed">Paid and confirmed</option><option value="all">All registrations</option></select></label><button className="btn-primary self-end">Search</button></form><div className="mt-5 flex flex-wrap gap-3"><a href={csv} className="btn-secondary">Download Player CSV</a><a href={pdf} className="btn-secondary">Download PDF</a><PdfPreview src={`${pdf}&preview=1`}/></div>{error&&<p role="alert" className="mt-4 text-red-700">Unable to load players. Please refresh or contact the administrator.</p>}<section className="card mt-6 overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-bold">Player Details</h2><p className="mt-1 text-sm text-stone-500">{rows.length} registrations. Blank IDs or DOB mean the information is missing from the registration.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-sm"><thead className="bg-stone-100 text-left"><tr>{cols.map(c=><th key={c.key} className="p-3">{c.label}</th>)}<th className="p-3">Edit</th></tr></thead><tbody>{rows.length===0&&<tr><td colSpan={cols.length+1} className="p-5">No players match these filters.</td></tr>}{rows.map((r:any)=><tr key={r.id} className="border-t">{cols.map(c=><td key={c.key} className="p-3">{c.value(r)}</td>)}<td className="p-3"><RegistrationEntryEditor id={r.id} initial={editableEntry(r)} tournament={r.tournaments?.title||"Tournament"}/></td></tr>)}</tbody></table></div></section></div>;
}
