const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs');
const {randomUUID}=require('node:crypto'); const {load,FakeDB}=require('./payment-helpers.cjs');
const config=load('lib/paymentConfig.ts');
process.env.STRIPE_SECRET_KEY='sk_live_fixture'; process.env.VERCEL_ENV='production'; process.env.NEXT_PUBLIC_SITE_URL='https://www.aucklandknights.co.nz';
function fixture(){
 const member={id:randomUUID(),membership_id:null,first_name:'Player',last_name:'Fixture',email:'player@example.invalid',payment_status:'pending_payment',membership_status:'pending_payment',total_amount_cents:8000,stripe_checkout_session_id:'cs_live_memberfixture'};
 const db=new FakeDB(); db.tables.club_memberships=[structuredClone(member)]; db.tables.email_templates=[];
 let counter=1001,sends=[],fail=false;
 db.rpc=async(name,args)=>{if(name==='assign_membership_id'){const row=db.tables.club_memberships.find(m=>m.id===args.p_member_id); if(!row.membership_id)row.membership_id=`AKCC${String(counter++).padStart(5,'0')}`;return {data:row.membership_id,error:null};}return {data:null,error:{code:'PGRST202'}};};
 const payment=load('lib/membershipPayment.ts',{'@/lib/paymentConfig':config,'@/lib/email':{sendEmail:async input=>{if(fail)throw Error('Email fixture fail');sends.push(input);}}});
 const session={id:member.stripe_checkout_session_id,mode:'payment',status:'complete',payment_status:'paid',livemode:true,currency:'nzd',amount_total:8000,payment_intent:'pi_memberfixture',metadata:{type:'membership',membership_id:member.id}};
 return {member,db,payment,session,sends,setFail(v){fail=v;}};
}
test('paid membership gets ID, active status and fallback email without a template',async()=>{const f=fixture();const r=await f.payment.confirmMembershipPayment(f.db,f.session);assert.equal(r.membership_id,'AKCC01001');assert.equal(r.email_status,'sent');assert.ok(f.sends[0].text.includes('AKCC01001'));assert.match(f.db.tables.club_memberships[0].membership_end_date,/^\d{4}-12-31$/);});
test('replay retains membership ID and sends one email',async()=>{const f=fixture();await f.payment.confirmMembershipPayment(f.db,f.session);await f.payment.confirmMembershipPayment(f.db,f.session);assert.equal(f.sends.length,1);assert.equal(f.db.tables.payment_records.length,1);assert.equal(f.db.tables.club_memberships[0].membership_id,'AKCC01001');});
test('email failure remains retryable after membership is already paid',async()=>{const f=fixture();f.setFail(true);const r=await f.payment.confirmMembershipPayment(f.db,f.session);assert.equal(r.email_status,'failed');assert.equal(f.db.tables.club_memberships[0].membership_status,'active');f.setFail(false);assert.equal((await f.payment.confirmMembershipPayment(f.db,f.session)).email_status,'sent');assert.equal(f.sends.length,1);});
test('wrong amount, test mode, unpaid session and different checkout cannot activate',async()=>{for(const change of [{amount_total:1},{livemode:false},{payment_status:'unpaid'},{id:'cs_live_other'}]){const f=fixture();await assert.rejects(f.payment.confirmMembershipPayment(f.db,{...f.session,...change}));assert.equal(f.db.tables.club_memberships[0].membership_status,'pending_payment');}});
test('cancelled or refunded members cannot be reactivated by payment replay',async()=>{for(const change of [{payment_status:'refunded'},{membership_status:'cancelled'}]){const f=fixture();Object.assign(f.db.tables.club_memberships[0],change);await assert.rejects(f.payment.confirmMembershipPayment(f.db,f.session));}});
test('templates render values with HTML escaped',async()=>{const f=fixture();f.db.tables.email_templates=[{template_key:'membership_confirmation',is_active:true,subject:'Member {{membership_id}}',body:'Hello {{first_name}}'}];f.db.tables.club_memberships[0].first_name='<script>bad</script>';await f.payment.confirmMembershipPayment(f.db,f.session);assert.ok(f.sends[0].html.includes('&lt;script&gt;'));assert.ok(!f.sends[0].html.includes('<script>'));});
test('member search trims input and matches case-insensitive ID or literal email',()=>{const search=load('lib/memberSearch.ts');const calls=[];const q={ilike:(...args)=>{calls.push(args);return q;}};search.applyMemberSearch(q,' akcc01001 ');search.applyMemberSearch(q,'player_1@example.com');assert.equal(calls[0][0],'membership_id');assert.equal(calls[0][1],'akcc01001');assert.equal(calls[1][1],'player\\_1@example.com');});
test('membership numbering cannot be changed without admin permission',async()=>{const route=load('app/api/admin/membership-numbering/route.ts',{'@/lib/auth':{getCurrentAdmin:async()=>null},'@/lib/roles':{canAccess:()=>false},'@/lib/supabase/service':{}});assert.equal((await route.POST(new Request('https://example.invalid',{method:'POST',body:'{}'}))).status,403);});
test('numbering rejects invalid prefix and fractional start',async()=>{const route=load('app/api/admin/membership-numbering/route.ts',{'@/lib/auth':{getCurrentAdmin:async()=>({profile:{role:'admin'}})},'@/lib/roles':{canAccess:()=>true},'@/lib/supabase/service':{createSupabaseServiceClient(){throw Error('must not call');}}});for(const body of [{prefix:'bad prefix',start:1,digits:5},{prefix:'AKCC',start:1.5,digits:5}])assert.equal((await route.POST(new Request('https://example.invalid',{method:'POST',body:JSON.stringify(body)}))).status,400);});
test('numbering migration preserves IDs, handles replays, concurrent allocations and start changes',async()=>{
 const {PGlite}=require('@electric-sql/pglite');const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role;create table club_settings(id text primary key,membership_id_prefix text,updated_at timestamptz default now());insert into club_settings values('default','AKCC',now());create table club_memberships(id uuid primary key,membership_id text unique,payment_status text,updated_at timestamptz default now());`);
 await db.exec(fs.readFileSync('supabase/migration_v4_4_membership_numbering.sql','utf8'));
 const ids=[randomUUID(),randomUUID(),randomUUID(),randomUUID()];for(const id of ids)await db.query(`insert into club_memberships(id,payment_status)values($1,'paid')`,[id]);
 let first=(await db.query('select assign_membership_id($1) as id',[ids[0]])).rows[0].id;assert.equal(first,'AKCC01001');assert.equal((await db.query('select assign_membership_id($1) as id',[ids[0]])).rows[0].id,first);
 const assigned=await Promise.all(ids.slice(1,3).map(id=>db.query('select assign_membership_id($1) as id',[id])));assert.equal(new Set(assigned.map(r=>r.rows[0].id)).size,2);
 await db.query("select configure_membership_numbering('AKCC',1,5)");assert.equal((await db.query('select assign_membership_id($1) as id',[ids[3]])).rows[0].id,'AKCC01004');
 await db.query("select configure_membership_numbering('KNIGHT',42,4)");const extra=randomUUID();await db.query("insert into club_memberships(id,payment_status)values($1,'paid')",[extra]);assert.equal((await db.query('select assign_membership_id($1) as id',[extra])).rows[0].id,'KNIGHT0042');
 assert.equal((await db.query('select membership_id from club_memberships where id=$1',[ids[0]])).rows[0].membership_id,first);
 const unpaid=randomUUID();await db.query("insert into club_memberships(id,payment_status)values($1,'pending_payment')",[unpaid]);await assert.rejects(db.query('select assign_membership_id($1)',[unpaid]));
 const perms=(await db.query("select has_function_privilege('anon','assign_membership_id(uuid)','EXECUTE') as anon,has_function_privilege('service_role','assign_membership_id(uuid)','EXECUTE') as service")).rows[0];assert.equal(perms.anon,false);assert.equal(perms.service,true);
 await db.close();
});
test('legacy generator remains usable before migration and retains ID on concurrent calls',async()=>{const f=fixture();let count=1001;f.db.rpc=async name=>name==='assign_membership_id'?{error:{code:'PGRST202'}}:{data:`AKCC${String(count++).padStart(5,'0')}`};const ids=await Promise.all([f.payment.assignMembershipId(f.db,f.member),f.payment.assignMembershipId(f.db,f.member)]);assert.equal(ids[0],ids[1]);assert.equal(f.db.tables.club_memberships[0].membership_id,ids[0]);});
test('email retry does not renew an expired membership',async()=>{const f=fixture();f.db.tables.club_memberships[0].membership_end_date='2020-12-31';const r=await f.payment.confirmMembershipPayment(f.db,f.session);assert.equal(r.status,'expired');assert.equal(f.db.tables.club_memberships[0].membership_status,'expired');});
test('membership webhook requests retry when email fails after paid activation',async()=>{const f=fixture();f.setFail(true);process.env.STRIPE_WEBHOOK_SECRET='whsec_fixture';const route=load('app/api/stripe/webhook/route.ts',{'@/lib/stripe':{getStripe:()=>({webhooks:{constructEvent:()=>({id:'evt_fixture',type:'checkout.session.completed',data:{object:f.session}})}})},'@/lib/supabase/service':{createSupabaseServiceClient:()=>f.db},'@/lib/membershipPayment':f.payment,'@/lib/paymentConfig':config});const request=()=>new Request('https://example.invalid',{method:'POST',headers:{'stripe-signature':'fixture'},body:'{}'});assert.equal((await route.POST(request())).status,503);f.setFail(false);assert.equal((await route.POST(request())).status,200);assert.equal(f.sends.length,1);});
