const {test}=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm'); const ts=require('typescript');
function setup(responses, env={NZPOST_CLIENT_ID:'id',NZPOST_CLIENT_SECRET:'secret'}) {
 const calls=[];const exports={}; const code=ts.transpileModule(fs.readFileSync('lib/nzpostAddress.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 vm.runInNewContext(code,{exports,process:{env},Date,URLSearchParams,AbortSignal,fetch:async(url,options)=>{calls.push({url,options});const data=responses.shift();return {ok:data.status?data.status===200:true,status:data.status||200,json:async()=>data.body||data};}});
 return {api:exports,calls};
}
const auth={access_token:'private-token',expires_in:3600};
test('OAuth stays server-side, tokens reused and suggestions require IDs',async()=>{const {api,calls}=setup([auth,{success:true,addresses:[{DPID:123,FullAddress:'8 Water Lane'},{FullAddress:'invalid'}]},{success:true,addresses:[]}]);const results=await api.suggestNZPost('8 water');assert.equal(results.length,1);assert.equal(results[0].dpid,'123');await api.suggestNZPost('9 water');assert.equal(calls.length,3);assert.equal(calls[0].options.body.get('client_secret'),'secret');assert.equal(calls[1].options.headers.Authorization,'Bearer private-token');assert.equal(calls[1].options.cache,'no-store');assert.ok(!JSON.stringify(results).includes('private-token'));});
test('details preserve unit and rural address lines and leading-zero postcodes',async()=>{const {api}=setup([auth,{success:true,details:[{DPID:123,AddressLine1:'Flat 2 8 Water Lane',AddressLine2:'RD 1',AddressLine3:'Kaitaia 0410',CityTown:'Kaitaia',Postcode:'0410'}]}]);const a=await api.detailsNZPost('123');assert.equal(a.street_address,'Flat 2 8 Water Lane, RD 1');assert.equal(a.city,'Kaitaia');assert.equal(a.postcode,'0410');});
test('expired authorization is refreshed once',async()=>{const {api,calls}=setup([auth,{status:401},auth,{success:true,addresses:[]}]);await api.suggestNZPost('8 water');assert.equal(calls.length,4);});
test('missing credentials and invalid identifiers never call upstream',async()=>{const {api,calls}=setup([],{});await assert.rejects(api.suggestNZPost('8 water'));await assert.rejects(api.detailsNZPost('../secret'));assert.equal(calls.length,0);});
test('provider failure or wrong detail ID fails without guessed fields',async()=>{let {api}=setup([auth,{success:false,addresses:[]}]);await assert.rejects(api.suggestNZPost('8 water'));({api}=setup([auth,{success:true,details:[{DPID:99,AddressLine1:'Wrong address'}]}]));await assert.rejects(api.detailsNZPost('123'));});
