"use client";
import { useState } from "react";
import { formatMoney } from "@/lib/format";
export default function MembershipRenewal({ member, token, options, linkError }: { member: any; token?: string; options: any[]; linkError?: string }) {
 const [message,setMessage]=useState(linkError || "");const [busy,setBusy]=useState(false);
 const [option,setOption]=useState(options[0]?.key || "");const [terms,setTerms]=useState(false);
 async function recover(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);
  try {const res=await fetch('/api/membership/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),surname:data.get('surname')})});const result=await res.json();setMessage(result.error || result.message);}catch{setMessage('Unable to request a lookup email. Try again later.');}finally{setBusy(false);}
 }
 async function renew(e: React.FormEvent) {
  e.preventDefault();setBusy(true);
  try {const res=await fetch('/api/membership/renew',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({member_token:token,option_key:option,terms_accepted:terms})});const result=await res.json();if(res.ok && result.url)window.location.href=result.url;else setMessage(result.error || 'Unable to start renewal.');}catch{setMessage('Connection interrupted. If you paid, do not pay again. Contact the club.');}finally{setBusy(false);}
 }
 return <section className="card mb-8 p-6"><h2 className="text-2xl font-extrabold">Find Your Membership / Renew</h2>{member ? <div><p className="mt-3 font-bold">{member.first_name} {member.last_name} · {member.membership_id}</p><p className="mt-2">Membership expires: {member.membership_end_date || 'Contact the club'}</p><p className="mt-2 text-sm text-stone-600">Renewal keeps your membership ID. Your new period starts after your current expiry, or today if already expired. Membership becomes renewed only after payment is confirmed.</p><form onSubmit={renew} className="mt-4 space-y-4"><label className="block"><span className="label">Membership option and fee</span><select value={option} onChange={e=>setOption(e.target.value)} required className="input mt-1">{options.map(o=><option key={o.key} value={o.key}>{o.name} — {formatMoney(o.fee_cents)} ({o.valid_until_month ? `ends in month ${o.valid_until_month}` : `${o.validity_months || 12} months`})</option>)}</select></label><p className="text-sm">Fees are not refundable or transferable once processed. Club rules require respectful behaviour and quiet play; parents/guardians remain responsible for children.</p><label className="flex gap-2"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required />I accept the membership terms.</label><button disabled={busy || !options.length} className="btn-primary">{busy ? 'Preparing renewal…' : 'Renew & Pay'}</button></form></div> : <form onSubmit={recover} className="mt-4"><p className="text-sm text-stone-600">Enter your registered email. Add a surname to find a particular player in a family. We will email your membership ID and a secure renewal link; player records are not listed publicly.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className="label">Registered email *</span><input name="email" type="email" maxLength={254} required className="input mt-1" /></label><label><span className="label">Player surname (optional)</span><input name="surname" maxLength={100} className="input mt-1" /></label></div><button disabled={busy} className="btn-primary mt-4">{busy ? 'Sending…' : 'Find Membership / Email Renewal Link'}</button></form>}{message && <p role="status" className="mt-4 rounded-lg bg-stone-50 p-3 text-sm font-bold">{message}</p>}</section>;
}
