"use client";
import { useEffect,useRef } from "react";
import MeetingSummary from "@/components/MeetingSummary";
type PreviewField={name:string;label:string;type?:string;textarea?:boolean};
export default function ContentPreview({data,fields,onClose,onSave,busy,saveLabel}:{data:any;fields:PreviewField[];onClose:()=>void;onSave?:()=>void;busy:boolean;saveLabel:string}) {
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();},[]);
  const image=fields.find(f=>f.type==="image");
  const hidden=["slug","is_published","publish_to_social","publish_as_news","status","display_order","meeting_id","posted_at","social_platforms","platforms","name","title","person_name"];
  return <dialog ref={dialog} aria-labelledby="content-preview-title" onClose={onClose} onClick={e=>{if(e.target===e.currentTarget && !busy)dialog.current?.close();}} onCancel={e=>{if(busy)e.preventDefault();}} className="m-auto max-h-[90vh] w-[min(900px,95vw)] overflow-y-auto rounded-2xl bg-white p-0 shadow-xl backdrop:bg-black/50"><div className="sticky top-0 z-10 flex items-center justify-between gap-4 border-b bg-white p-4"><h2 id="content-preview-title" className="text-xl font-bold">Content preview</h2><button type="button" disabled={busy} onClick={()=>dialog.current?.close()} className="btn-secondary">Close</button></div><article className="p-6 sm:p-8">{image && data[image.name] && <img src={data[image.name]} alt="" className="mb-6 max-h-80 w-full rounded-lg object-contain"/>}<h3 className="text-3xl font-extrabold">{data.name || data.title || data.person_name || "Untitled"}</h3>{data.name && data.title && <p className="mt-2 font-semibold">{data.title}</p>}{fields.filter(f=>!hidden.includes(f.name) && !["image","checkbox","multi_options"].includes(f.type || "") && data[f.name]).map(f=><section key={f.name} className="mt-4"><p className="mb-1 text-xs font-bold uppercase text-slate-500">{f.label}</p>{f.type==="richtext" ? <MeetingSummary text={String(data[f.name])}/> : <p className="whitespace-pre-wrap break-words leading-7 text-slate-700">{String(data[f.name])}</p>}</section>)}{(data.platforms || data.social_platforms)?.length>0 && <p className="mt-5 text-sm text-slate-600">Platforms: {(data.platforms || data.social_platforms).join(", ")}</p>}</article>{onSave && <div className="sticky bottom-0 flex justify-end gap-3 border-t bg-white p-4"><button type="button" disabled={busy} onClick={()=>dialog.current?.close()} className="btn-secondary">Back to editing</button><button type="button" disabled={busy} onClick={onSave} className="btn-primary">{busy ? "Saving..." : saveLabel}</button></div>}</dialog>;
}
