"use client";
import {useRef,useState} from "react";
import {Pencil,X} from "lucide-react";
import {ENTRY_FIELDS} from "@/lib/tournamentEntryEditing";
export default function RegistrationEntryEditor({id,initial,tournament}:{id:string;initial:Record<string,string>;tournament:string}){
 const dialog=useRef<HTMLDialogElement>(null);const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/admin/tournament-registrations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,payload:form})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to save.");window.location.reload();}catch(e:any){setError(e.message||"Unable to save.");}finally{setBusy(false);}}
 return <><button type="button" onClick={()=>{setForm(initial);setError("");dialog.current?.showModal();}} title="Edit tournament entry" aria-label="Edit tournament entry" className="inline-flex h-9 w-9 shrink-0 items-center justify-center bg-stone-900 text-white"><Pencil size={16}/></button><dialog ref={dialog} aria-label="Edit tournament entry" className="m-auto max-h-[90vh] w-[94vw] max-w-3xl overflow-y-auto rounded-xl border-0 bg-white p-0 shadow-xl backdrop:bg-black/60"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-bold">Edit Tournament Entry</h2><p className="text-sm text-stone-600">{tournament}</p></div><button type="button" aria-label="Close editor" onClick={()=>dialog.current?.close()}><X/></button></div><form onSubmit={save} className="p-5"><div className="grid gap-4 sm:grid-cols-2">{ENTRY_FIELDS.map(f=><label key={f.key}><span className="admin-label">{f.label}{f.required?" *":""}</span><input name={f.key} type={f.type||"text"} required={f.required} value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})} className="admin-input" min={f.type==="number"?0:undefined} max={f.type==="number"?4000:undefined}/></label>)}</div>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-5 flex gap-3"><button disabled={busy} className="btn-primary">{busy?"Saving...":"Save changes"}</button><button type="button" className="btn-secondary" onClick={()=>dialog.current?.close()}>Cancel</button></div></form></dialog></>;
}
